[project]
name = "pytemplatecli"
version = "0.4.0"
description = "Python Template System - Make projects with prebuilt templates"
readme = "README.md"
authors = [
    {name = "radin6262", email = "none@gmail.com"}
]
license = "MIT"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Code Generators",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "click>=8.0.0",
    "requests>=2.28.0",
    "tqdm>=4.65.0",
]

[project.scripts]
pytemplate = "pytemplate.cli:main"

[project.urls]
Homepage = "https://github.com/radin6262/pytemplate"
Repository = "https://github.com/radin6262/pytemplate"
Issues = "https://github.com/radin6262/pytemplate"

[tool.setuptools.packages.find]
where = ["src"]